import 'package:flutter/cupertino.dart';

class Autogenerated {
  Result? result;
  Null targetUrl;
  bool? success;
  Null error;
  bool? unAuthorizedRequest;
  bool? bAbp;

  Autogenerated(
      {this.result,
      this.targetUrl,
      this.success,
      this.error,
      this.unAuthorizedRequest,
      this.bAbp});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result =
        json['result'] != null ? new Result.fromJson(json['result']) : null;
    targetUrl = json['targetUrl'];
    success = json['success'];
    error = json['error'];
    unAuthorizedRequest = json['unAuthorizedRequest'];
    bAbp = json['__abp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result!.toJson();
    }
    data['targetUrl'] = this.targetUrl;
    data['success'] = this.success;
    data['error'] = this.error;
    data['unAuthorizedRequest'] = this.unAuthorizedRequest;
    data['__abp'] = this.bAbp;
    return data;
  }
}

class Result {
  int? totalCount;
  List<Order>? items;

  Result({this.totalCount, this.items});

  Result.fromJson(Map<String, dynamic> json) {
    totalCount = json['totalCount'];
    if (json['items'] != null) {
      items = <Order>[];
      json['items'].forEach((v) {
        items!.add(new Order.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['totalCount'] = this.totalCount;
    if (this.items != null) {
      data['items'] = this.items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Order with ChangeNotifier {
  String? productId;
  Product? product;
  int? userId;
  User? user;
  int? gst;
  int? shippingCost;
  int? tiveleFee;
  int? totalAmount;
  int? quantity;
  String? referenceId;
  String? deliveryTime;
  String? driverAccountId;
  String? id;

  Order(
      {this.productId,
      this.product,
      this.userId,
      this.user,
      this.gst,
      this.shippingCost,
      this.tiveleFee,
      this.totalAmount,
      this.quantity,
      this.referenceId,
      this.deliveryTime,
      this.driverAccountId,
      this.id});

  Order.fromJson(Map<String, dynamic> json) {
    productId = json['productId'];
    product =
        json['product'] != null ? new Product.fromJson(json['product']) : null;
    userId = json['userId'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
    gst = json['gst'];
    shippingCost = json['shippingCost'];
    tiveleFee = json['tiveleFee'];
    totalAmount = json['totalAmount'];
    quantity = json['quantity'];
    referenceId = json['referenceId'];
    deliveryTime = json['deliveryTime'];
    driverAccountId = json['driverAccountId'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['productId'] = this.productId;
    if (this.product != null) {
      data['product'] = this.product!.toJson();
    }
    data['userId'] = this.userId;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    data['gst'] = this.gst;
    data['shippingCost'] = this.shippingCost;
    data['tiveleFee'] = this.tiveleFee;
    data['totalAmount'] = this.totalAmount;
    data['quantity'] = this.quantity;
    data['referenceId'] = this.referenceId;
    data['deliveryTime'] = this.deliveryTime;
    data['driverAccountId'] = this.driverAccountId;
    data['id'] = this.id;
    return data;
  }
}

class Product {
  String? name;
  int? oldPrice;
  int? newPrice;
  String? description;
  int? gst;
  String? productCategoryId;
  //Null productCategory;
  ProductImage? productImage;
  String? productImageId;
  String? businessAccountId;
  //Null businessAccount;
  int? productViewedCount;
  int? productRequestedCount;
  Null likeCount;
  Null ratingAverage;
  int? distance;
  String? id;

  Product(
      {this.name,
      this.oldPrice,
      this.newPrice,
      this.description,
      this.gst,
      this.productCategoryId,
      //this.productCategory,
      this.productImage,
      this.productImageId,
      this.businessAccountId,
      //this.businessAccount,
      this.productViewedCount,
      this.productRequestedCount,
      this.likeCount,
      this.ratingAverage,
      this.distance,
      this.id});

  Product.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    oldPrice = json['oldPrice'];
    newPrice = json['newPrice'];
    description = json['description'];
    gst = json['gst'];
    productCategoryId = json['productCategoryId'];
    //productCategory = json['productCategory'];
    productImage = json['productImage'] != null
        ? new ProductImage.fromJson(json['productImage'])
        : null;
    productImageId = json['productImageId'];
    businessAccountId = json['businessAccountId'];
    //businessAccount = json['businessAccount'];
    productViewedCount = json['productViewedCount'];
    productRequestedCount = json['productRequestedCount'];
    likeCount = json['likeCount'];
    ratingAverage = json['ratingAverage'];
    distance = json['distance'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['oldPrice'] = this.oldPrice;
    data['newPrice'] = this.newPrice;
    data['description'] = this.description;
    data['gst'] = this.gst;
    data['productCategoryId'] = this.productCategoryId;
    //data['productCategory'] = this.productCategory;
    if (this.productImage != null) {
      data['productImage'] = this.productImage!.toJson();
    }
    data['productImageId'] = this.productImageId;
    data['businessAccountId'] = this.businessAccountId;
    //data['businessAccount'] = this.businessAccount;
    data['productViewedCount'] = this.productViewedCount;
    data['productRequestedCount'] = this.productRequestedCount;
    data['likeCount'] = this.likeCount;
    data['ratingAverage'] = this.ratingAverage;
    data['distance'] = this.distance;
    data['id'] = this.id;
    return data;
  }
}

class ProductImage {
  String? contentType;
  int? length;
  String? name;
  String? fileName;
  String? fileKey;
  String? url;
  String? id;

  ProductImage(
      {this.contentType,
      this.length,
      this.name,
      this.fileName,
      this.fileKey,
      this.url,
      this.id});

  ProductImage.fromJson(Map<String, dynamic> json) {
    contentType = json['contentType'];
    length = json['length'];
    name = json['name'];
    fileName = json['fileName'];
    fileKey = json['fileKey'];
    url = json['url'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['contentType'] = this.contentType;
    data['length'] = this.length;
    data['name'] = this.name;
    data['fileName'] = this.fileName;
    data['fileKey'] = this.fileKey;
    data['url'] = this.url;
    data['id'] = this.id;
    return data;
  }
}

class User {
  String? userName;
  String? name;
  String? surname;
  String? emailAddress;
  bool? isActive;
  String? fullName;
  Null lastLoginTime;
  String? creationTime;
  Null roleNames;
  String? userProfileId;
  Null userProfile;
  int? id;

  User(
      {this.userName,
      this.name,
      this.surname,
      this.emailAddress,
      this.isActive,
      this.fullName,
      this.lastLoginTime,
      this.creationTime,
      this.roleNames,
      this.userProfileId,
      this.userProfile,
      this.id});

  User.fromJson(Map<String, dynamic> json) {
    userName = json['userName'];
    name = json['name'];
    surname = json['surname'];
    emailAddress = json['emailAddress'];
    isActive = json['isActive'];
    fullName = json['fullName'];
    lastLoginTime = json['lastLoginTime'];
    creationTime = json['creationTime'];
    roleNames = json['roleNames'];
    userProfileId = json['userProfileId'];
    userProfile = json['userProfile'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['userName'] = this.userName;
    data['name'] = this.name;
    data['surname'] = this.surname;
    data['emailAddress'] = this.emailAddress;
    data['isActive'] = this.isActive;
    data['fullName'] = this.fullName;
    data['lastLoginTime'] = this.lastLoginTime;
    data['creationTime'] = this.creationTime;
    data['roleNames'] = this.roleNames;
    data['userProfileId'] = this.userProfileId;
    data['userProfile'] = this.userProfile;
    data['id'] = this.id;
    return data;
  }
}
