import 'package:flutter/cupertino.dart';
import 'package:e_commerce_foods/models/BusinessUser/businessUser.dart';

class Autogenerated {
  Result? result;
  Null targetUrl;
  bool? success;
  Null error;
  bool? unAuthorizedRequest;
  bool? bAbp;

  Autogenerated(
      {this.result,
      this.targetUrl,
      this.success,
      this.error,
      this.unAuthorizedRequest,
      this.bAbp});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result =
        json['result'] != null ? new Result.fromJson(json['result']) : null;
    targetUrl = json['targetUrl'];
    success = json['success'];
    error = json['error'];
    unAuthorizedRequest = json['unAuthorizedRequest'];
    bAbp = json['__abp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result!.toJson();
    }
    data['targetUrl'] = this.targetUrl;
    data['success'] = this.success;
    data['error'] = this.error;
    data['unAuthorizedRequest'] = this.unAuthorizedRequest;
    data['__abp'] = this.bAbp;
    return data;
  }
}

class Result {
  int? totalCount;
  List<Reviews>? items;

  Result({this.totalCount, this.items});

  Result.fromJson(Map<String, dynamic> json) {
    totalCount = json['totalCount'];
    if (json['items'] != null) {
      items = <Reviews>[];
      json['items'].forEach((v) {
        items!.add(new Reviews.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['totalCount'] = this.totalCount;
    if (this.items != null) {
      data['items'] = this.items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Reviews with ChangeNotifier {
  int? userId;
  BusinessUser? user;
  String? productId;
  //Null product;
  String? comment;
  double? rating;
  String? id;

  Reviews(
      {this.userId,
      this.user,
      this.productId,
      //this.product,
      this.comment,
      this.rating,
      this.id});

  Reviews.fromJson(Map<String, dynamic> json) {
    userId = json['userId'];
    user =
        json['user'] != null ? new BusinessUser.fromJson(json['user']) : null;
    productId = json['productId'];
    //product = json['product'];
    comment = json['comment'];
    rating = json['rating'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['userId'] = this.userId;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    data['productId'] = this.productId;
    //data['product'] = this.product;
    data['comment'] = this.comment;
    data['rating'] = this.rating;
    data['id'] = this.id;
    return data;
  }
}
