import 'package:flutter/cupertino.dart';

class Autogenerated {
  Result? result;
  Null targetUrl;
  bool? success;
  Null error;
  bool? unAuthorizedRequest;
  bool? bAbp;

  Autogenerated(
      {this.result,
      this.targetUrl,
      this.success,
      this.error,
      this.unAuthorizedRequest,
      this.bAbp});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result =
        json['result'] != null ? new Result.fromJson(json['result']) : null;
    targetUrl = json['targetUrl'];
    success = json['success'];
    error = json['error'];
    unAuthorizedRequest = json['unAuthorizedRequest'];
    bAbp = json['__abp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result!.toJson();
    }
    data['targetUrl'] = this.targetUrl;
    data['success'] = this.success;
    data['error'] = this.error;
    data['unAuthorizedRequest'] = this.unAuthorizedRequest;
    data['__abp'] = this.bAbp;
    return data;
  }
}

class Result {
  int? totalCount;
  List<ProductCategory>? items;

  Result({this.totalCount, this.items});

  Result.fromJson(Map<String, dynamic> json) {
    totalCount = json['totalCount'];
    if (json['items'] != null) {
      items = <ProductCategory>[];
      json['items'].forEach((v) {
        items!.add(new ProductCategory.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['totalCount'] = this.totalCount;
    if (this.items != null) {
      data['items'] = this.items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ProductCategory with ChangeNotifier {
  String? name;
  String? productCategoryImageId;
  ProductCategoryImage? productCategoryImage;
  String? id;
  bool isSelected = false;
  ProductCategory(
      {this.name,
      this.productCategoryImageId,
      this.productCategoryImage,
      this.id});

  ProductCategory.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    productCategoryImageId = json['productCategoryImageId'];
    productCategoryImage = json['productCategoryImage'] != null
        ? new ProductCategoryImage.fromJson(json['productCategoryImage'])
        : null;
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['productCategoryImageId'] = this.productCategoryImageId;
    if (this.productCategoryImage != null) {
      data['productCategoryImage'] = this.productCategoryImage!.toJson();
    }
    data['id'] = this.id;
    return data;
  }
}

class ProductCategoryImage {
  String? contentType;
  int? length;
  String? name;
  String? fileName;
  String? fileKey;
  String? url;
  String? id;

  ProductCategoryImage(
      {this.contentType,
      this.length,
      this.name,
      this.fileName,
      this.fileKey,
      this.url,
      this.id});

  ProductCategoryImage.fromJson(Map<String, dynamic> json) {
    contentType = json['contentType'];
    length = json['length'];
    name = json['name'];
    fileName = json['fileName'];
    fileKey = json['fileKey'];
    url = json['url'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['contentType'] = this.contentType;
    data['length'] = this.length;
    data['name'] = this.name;
    data['fileName'] = this.fileName;
    data['fileKey'] = this.fileKey;
    data['url'] = this.url;
    data['id'] = this.id;
    return data;
  }
}
