import 'package:flutter/cupertino.dart';

class Autogenerated {
  Result? result;
  Null targetUrl;
  bool? success;
  Null error;
  bool? unAuthorizedRequest;
  bool? bAbp;

  Autogenerated(
      {this.result,
      this.targetUrl,
      this.success,
      this.error,
      this.unAuthorizedRequest,
      this.bAbp});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result =
        json['result'] != null ? new Result.fromJson(json['result']) : null;
    targetUrl = json['targetUrl'];
    success = json['success'];
    error = json['error'];
    unAuthorizedRequest = json['unAuthorizedRequest'];
    bAbp = json['__abp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result!.toJson();
    }
    data['targetUrl'] = this.targetUrl;
    data['success'] = this.success;
    data['error'] = this.error;
    data['unAuthorizedRequest'] = this.unAuthorizedRequest;
    data['__abp'] = this.bAbp;
    return data;
  }
}

class Result {
  int? totalCount;
  List<Card>? items;

  Result({this.totalCount, this.items});

  Result.fromJson(Map<String, dynamic> json) {
    totalCount = json['totalCount'];
    if (json['items'] != null) {
      items = [];
      json['items'].forEach((v) {
        items!.add(new Card.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['totalCount'] = this.totalCount;
    if (this.items != null) {
      data['items'] = this.items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Card with ChangeNotifier {
  String? cardNumber;
  String? bankName;
  String? firstName;
  String? lastName;
  String? expiryDate;
  String? cvv;
  int? userId;
  String? id;

  Card(
      {this.cardNumber,
      this.bankName,
      this.firstName,
      this.lastName,
      this.expiryDate,
      this.cvv,
      this.userId,
      this.id});

  Card.fromJson(Map<String, dynamic> json) {
    cardNumber = json['cardNumber'];
    bankName = json['bankName'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    expiryDate = json['expiryDate'];
    cvv = json['cvv'];
    userId = json['userId'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['cardNumber'] = this.cardNumber;
    data['bankName'] = this.bankName;
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['expiryDate'] = this.expiryDate;
    data['cvv'] = this.cvv;
    data['userId'] = this.userId;
    data['id'] = this.id;
    return data;
  }
}
